# Generated by Django 6.0.4 on 2026-04-20 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipplacement',
            name='academic_supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_placements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internshipplacement',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement_as_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internshipplacement',
            name='workplace_supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplace_placements', to=settings.AUTH_USER_MODEL),
        ),
    ]
