# Generated by Django 6.0.3 on 2026-05-07 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0003_alter_internshipplacement_academic_supervisor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internshipplacement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='internshipplacement',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internshipplacement',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internshipplacement',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_placements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internshipplacement',
            name='company_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='internshipplacement',
            name='company_contact_person',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='internshipplacement',
            name='company_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='internshipplacement',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='internshipplacement',
            name='position_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='internshipplacement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='internshipplacement',
            name='academic_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_placements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internshipplacement',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('completed', 'Completed')], default='pending_approval', max_length=20),
        ),
        migrations.AlterField(
            model_name='internshipplacement',
            name='workplace_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workplace_placements', to=settings.AUTH_USER_MODEL),
        ),
    ]
