# Generated by Django 6.0.4 on 2026-04-20 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklylogmodel',
            name='student',
        ),
    ]
