# Generated by Django 6.0.3 on 2026-05-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_logs', '0002_remove_weeklylogmodel_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklylogmodel',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='weekly_logs/'),
        ),
        migrations.AddField(
            model_name='weeklylogmodel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weeklylogmodel',
            name='hours_spent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='weeklylogmodel',
            name='log_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
