# Generated by Django 6.0.4 on 2026-06-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_logs', '0004_alter_weeklylogmodel_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklylogmodel',
            name='workplace_reviewer_name',
            field=models.CharField(blank=True, help_text='Name of the workplace supervisor who reviewed this log', max_length=150, null=True),
        ),
    ]
