# Generated by Django 6.0.3 on 2026-06-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_logs', '0005_weeklylogmodel_workplace_reviewer_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklylogmodel',
            options={'ordering': ['-week_number', '-created_at']},
        ),
        migrations.AddField(
            model_name='weeklylogmodel',
            name='academic_evaluation_date',
            field=models.DateTimeField(blank=True, help_text='Date when academic supervisor evaluated the log', null=True),
        ),
        migrations.AddField(
            model_name='weeklylogmodel',
            name='academic_evaluator_name',
            field=models.CharField(blank=True, help_text='Name of the academic supervisor who evaluated this log', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='weeklylogmodel',
            name='academic_supervisor_comment',
            field=models.TextField(blank=True, help_text="Academic supervisor's evaluation comments"),
        ),
        migrations.AddField(
            model_name='weeklylogmodel',
            name='marks_awarded',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Marks/Grade awarded by academic supervisor', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='weeklylogmodel',
            name='workplace_review_date',
            field=models.DateTimeField(blank=True, help_text='Date when workplace supervisor reviewed the log', null=True),
        ),
        migrations.AddField(
            model_name='weeklylogmodel',
            name='workplace_supervisor_comment',
            field=models.TextField(blank=True, help_text="Workplace supervisor's remarks and comments"),
        ),
        migrations.AlterField(
            model_name='weeklylogmodel',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted - Awaiting Workplace Review'), ('AUTHORIZED', 'Authorized - Ready for Academic Submission'), ('PENDING_EVALUATION', 'Pending Academic Evaluation'), ('EVALUATED', 'Evaluated'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklylogmodel',
            name='supervisor_comment',
            field=models.TextField(blank=True, help_text='General supervisor comments (legacy field)'),
        ),
    ]
