# Generated by Django 6.0.4 on 2026-04-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('workplace_supervisor', 'Workplace Supervisor'), ('academic_supervisor', 'Academic Supervisor'), ('admin', 'Administrator')], default='student', max_length=20),
        ),
    ]
