# Generated by Django 6.0.3 on 2026-06-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company name for workplace supervisors', max_length=200, null=True),
        ),
    ]
