# Generated by Django 6.0.3 on 2026-05-07 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('placement_submitted', 'Placement Submitted'), ('placement_approved', 'Placement Approved'), ('placement_rejected', 'Placement Rejected'), ('supervisor_assigned', 'Supervisor Assigned'), ('log_submitted', 'Log Submitted'), ('log_reviewed', 'Log Reviewed'), ('log_approved', 'Log Approved'), ('log_rejected', 'Log Rejected'), ('evaluation_submitted', 'Evaluation Submitted')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_placement_id', models.IntegerField(blank=True, null=True)),
                ('related_log_id', models.IntegerField(blank=True, null=True)),
                ('related_evaluation_id', models.IntegerField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
