# Generated by Django 6.0.3 on 2026-05-07 09:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_initial'),
        ('placements', '0004_alter_internshipplacement_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punctuality_regularity', models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Below Average'), (1, 'Poor'), (0, 'N/A - Not Applicable')], help_text='Punctuality & Regularity', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('punctuality_remarks', models.TextField(blank=True, null=True)),
                ('communication_skills', models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Below Average'), (1, 'Poor'), (0, 'N/A - Not Applicable')], help_text='Communication Skills (Verbal/Written)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('communication_remarks', models.TextField(blank=True, null=True)),
                ('professional_attitude', models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Below Average'), (1, 'Poor'), (0, 'N/A - Not Applicable')], help_text='Professional Attitude & Behaviour', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('professional_remarks', models.TextField(blank=True, null=True)),
                ('teamwork_ability', models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Below Average'), (1, 'Poor'), (0, 'N/A - Not Applicable')], help_text='Ability to Work in a Team', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('teamwork_remarks', models.TextField(blank=True, null=True)),
                ('adaptability', models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Below Average'), (1, 'Poor'), (0, 'N/A - Not Applicable')], help_text='Adaptability to Work Environment', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('adaptability_remarks', models.TextField(blank=True, null=True)),
                ('analytical_skills', models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Below Average'), (1, 'Poor'), (0, 'N/A - Not Applicable')], help_text='Analytical & Problem-Solving Skills', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('analytical_remarks', models.TextField(blank=True, null=True)),
                ('initiative_willingness', models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Below Average'), (1, 'Poor'), (0, 'N/A - Not Applicable')], help_text='Initiative and Willingness to Learn', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('initiative_remarks', models.TextField(blank=True, null=True)),
                ('work_quality', models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Below Average'), (1, 'Poor'), (0, 'N/A - Not Applicable')], help_text='Quality of Work Delivered', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('work_quality_remarks', models.TextField(blank=True, null=True)),
                ('technical_knowledge', models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Below Average'), (1, 'Poor'), (0, 'N/A - Not Applicable')], help_text='Technical Knowledge Related to the Field', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('technical_remarks', models.TextField(blank=True, null=True)),
                ('overall_contribution', models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Below Average'), (1, 'Poor'), (0, 'N/A - Not Applicable')], help_text='Overall Contribution to the Organization', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('overall_remarks', models.TextField(blank=True, null=True)),
                ('general_comments', models.TextField(blank=True, help_text="General comments about the student's performance", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='evaluation',
            name='unique_field_combination',
        ),
        migrations.RemoveField(
            model_name='evaluationscore',
            name='evaluation',
        ),
        migrations.RemoveField(
            model_name='evaluationscore',
            name='criteria',
        ),
        migrations.AddField(
            model_name='internshipevaluation',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internshipevaluation',
            name='placement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='placements.internshipplacement'),
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='evaluator',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='placement',
        ),
        migrations.DeleteModel(
            name='EvaluationCriteria',
        ),
        migrations.DeleteModel(
            name='EvaluationScore',
        ),
        migrations.AlterUniqueTogether(
            name='internshipevaluation',
            unique_together={('placement', 'evaluator')},
        ),
        migrations.DeleteModel(
            name='Evaluation',
        ),
    ]
